services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:8002"
    depends_on:
      - backend

  backend:
    build: ./backend
    restart: always
    ports:
      - "80:8001"
    depends_on:
      - crm

  crm:
    build: ./crm
    restart: always
    ports:
      - "80:8003"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: